### ISSUE TITLE
Can't compile with go 1.11

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#665]
```
# github.com/ethereumproject/go-ethereum/console
console/console.go:117:43: undefined: jsre.BigNumber_JS
console/console.go:120:38: undefined: jsre.Web3_JS
```
